api/urls.py
from django.urls import path
from .views import boards
from .views import BoardDetailView
from .views import comments

urlpatterns = [
    path('boards/<int:pk>/comments/', comments),
    path('boards/<int:pk>/', BoardDetailView.as_view()),
    path('boards/', boards),
]

board/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
    path('api/', include('api.urls')),
    path('', include('main.urls')),
]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))
    urlpatterns += static (settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
import imp
from django.urls import path
from .views import *

app_name = 'main'

urlpatterns = [
     path('accounts/logout/', BLogoutView.as_view(), name='logout'),
     path('accounts/login/', BLoginView.as_view(), name='login'),    
     path('account/profile/change/<int:pk>/', profile_board_change, name='profile_board_change'),
     path('account/profile/delete/<int:pk>/', profile_board_delete, name='profile_board_delete'),
     path('account/profile/add/', profile_board_add, name='profile_board_add'),
     path('accouts/profile/<int:pk>/', profile_board_detail, name='profile_board_detail'),
     path('<int:rubric_pk>/<int:pk>/', detail, name='detail'),
     path('accounts/password/change/', BPasswordChangeView.as_view(), name='password_change'),
     path('account/profile/delete/', DeleteUserView.as_view(), name='profile_delete'),
     path('account/profile/change/', ChangeUserInfoView.as_view(), name='profile_change'),
     path('accounts/profile/', profile, name='profile'),
     path('accounts/register/activate/<str:sign>/', user_activate, name='register_activate'),
     path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'), 
     path('accounts/register/', RegisterUserView.as_view(), name='register'),
     path('<int:pk>/', by_rubric, name='by_rubric'),
     path('<str:page>/', other_page, name='other'),
     path('', index, name='index'),
]

main/forms.py
from ast import keyword
from dataclasses import fields
from email import message
from django import forms
from django.urls import reverse_lazy
from .models import AdvUser
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError
from .apps import user_registered
from .models import SuperRubric, SubRubric
from django.forms import inlineformset_factory
from .models import Board, AdditionalImage
from captcha.fields import CaptchaField
from .models import Comment

class ChangeUserInfoForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Адрес электронной почты')

    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'first_name', 'last_name', 'send_messages')

class RegisterUserForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Адресс электронной почты')
    password_1 = forms.CharField(label='Пароль', 
        widget=forms.PasswordInput,
        help_text=password_validation.password_validators_help_text_html())
    password_2 = forms.CharField(label='Пароль (повторно)',
        widget=forms.PasswordInput,
        help_text='Введите пароль повторно для проверки')
        # поля формы входа

    def clean_password_1(self):
        password_1 = self.cleaned_data['password_1']
        if password_1:
            password_validation.validate_password(password_1)
        return password_1
        # валидация пароля

    def clean(self):
        super().clean()
        password_1 = self.cleaned_data['password_1']
        password_2 = self.cleaned_data['password_2']
        if password_1 and password_2 and password_1 != password_2:
            errors = {'password_2': 
                ValidationError('Введенные пароли не совпадают', 
                code='password_mismatch')}
            raise ValidationError(errors)
        # проверка совпадения двух паролей

    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_active = False
        user.is_activated = False
        if commit:
            user.save()
        user_registered.send(RegisterUserForm, instance=user)
        return user

    class Meta:
        model = AdvUser
        fields = ('username', 'email',
            'password_1', 'password_2',
            'first_name', 'last_name', 'send_messages')

class SubRubricForm(forms.ModelForm):
    super_rubric = forms.ModelChoiceField(queryset=SuperRubric.objects.all(),
        empty_label=None, label='Надрубрика',
        required=True)
    # empty_label=None убирает пустой пункт из выбора подрубрик
    
    class Meta:
        model = SubRubric
        fields = '__all__'

class SearchForm(forms.Form):
    keyword = forms.CharField(required=False, max_length=40, label='Введите запрос')
    # форма поиска по сайту

class BoardForm(forms.ModelForm):
    class Meta:
        model = Board
        fields = '__all__'
        widgets = {'author': forms.HiddenInput}

AIFormSet = inlineformset_factory(Board, AdditionalImage, fields='__all__')
# наборформ для ввода объявления включающий все поля и загрузку изображений

class UserCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = {'is_active'}
        widgets = {'board': forms.HiddenInput}

class GuestCommentForm(forms.ModelForm):
    captcha = CaptchaField(label='Введите текст с картинки', error_messages={'invalid':'Текст введён некорректно'})

    class Meta:
        model = Comment
        exclude = {'is_active'}
        widgets = {'board':forms.HiddenInput}

main/views.py
from ast import Return, keyword
from multiprocessing import context
from re import template
from django.shortcuts import render
from django.http import HttpResponse, Http404
from django.template import TemplateDoesNotExist
from django.template.loader import get_template
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import UpdateView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from .models import AdvUser
from .forms import ChangeUserInfoForm
from django.contrib.auth.views import PasswordChangeView
from django.views.generic.edit import CreateView
from .forms import RegisterUserForm
from django.views.generic.base import TemplateView
from django.core.signing import BadSignature
from .utilities import signer
from django.views.generic.edit import DeleteView
from django.contrib.auth import logout
from django.contrib import messages
from django.core.paginator import Paginator
from django.db.models import Q
from .models import SubRubric, Board
from .forms import SearchForm
from django.shortcuts import redirect
from .forms import BoardForm, AIFormSet
from .models import Comment
from .forms import UserCommentForm, GuestCommentForm

def index(request):
    boards = Board.objects.filter(is_active=True)[:10]
    context = {'boards': boards}
    return render(request, 'main/index.html', context)
    # вывод последних 10 сообщений

def other_page(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))

class BLoginView(LoginView):
    template_name = 'main/login.html'

@login_required
def profile(request):
    boards = Board.objects.filter(author=request.user.pk)
    # фильтрация по значению поля "автор"
    context = {'boards': boards}
    return render(request, 'main/profile.html', context)

class BLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'main/logout.html'
# LoginRequiredMixin добавлен по тому что страница выхода доступна только зарегистрирванным пользователям

class ChangeUserInfoView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = AdvUser
    template_name = 'main/change_user_info.html'
    form_class = ChangeUserInfoForm
    success_url = reverse_lazy('main:profile')
    success_message = 'Данные пользователя изменены'

    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)
    # получение ключа текущего пользователя

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)
    # извлечение исправляемой записи

class BPasswordChangeView(SuccessMessageMixin, LoginRequiredMixin, PasswordChangeView):
    template_name = 'main/password_change.html'
    success_url = reverse_lazy('main:profile')
    success_message = 'Пароль пользователя изменен'
    # смена пароль пользователя

class RegisterUserView(CreateView):
    model = AdvUser
    template_name = 'main/register_user.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('main:register_done')
    # класс регистрирующий пользователя

class RegisterDoneView(TemplateView):
    template_name = 'main/register_done.html'
    # вывод сообщения об успешной активации

def user_activate(request, sign):
    try:
        username = signer.unsign(sign)
    except BadSignature:
        return render(request, 'main/bad_signature.html')
    user = get_object_or_404(AdvUser, username=username)
    if user.is_activated:
        template = 'main/user_is_activated.html'
    else:
        template = 'main/activation_done.html'
        user.is_active =True
        user.is_activated = True
        user.save()
    return render(request, template)
    # проверка активации

class DeleteUserView(LoginRequiredMixin, DeleteView):
    model = AdvUser
    template_name = 'main/delete_user.html'
    success_url = reverse_lazy('main:index')

    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)
        # сохранение ключа текущего пользователя

    def post(self, request, *args, **kwargs):
        logout(request)
        messages.add_message(request, messages.SUCCESS, 'Пользователь удалён')
        return super().post(request, *args, **kwargs)
        # выход, всплывающее сообщение об удалении

    def get_object(self,queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)
        # поиск по ключу из setup пользователя подлежащего удалению

def by_rubric(request, pk):
    rubric = get_object_or_404(SubRubric, pk=pk)
    boards = Board.objects.filter(is_active=True, rubric=pk)

    # фильтрация объявлений по поисковому запросу
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        q = Q(title__icontains=keyword) | Q(content__icontains=keyword)
        boards = boards.filter(q)
    else:
        keyword = ''
    form = SearchForm(initial={'keyword':keyword}) # для вывода на экран
    paginator = Paginator(boards,2) # 2 - количество записей для проверки пагинатора
    if 'page' in request.GET:
        page_number = request.GET['page']
    else:
        page_number = 1
    page = paginator.get_page(page_number)
    context = {'rubric': rubric,
        'page': page,
        'boards': page.object_list,
        'form': form}
    return render(request, 'main/by_rubric.html', context)

def detail(request, rubric_pk, pk):
    board = Board.objects.get(pk=pk)
    ais = board.additionalimage_set.all() # дополнительные иллюстрации
    comments = Comment.objects.filter(board=pk, is_active=True)
    initial = {'board': board.pk}
    if request.user.is_authenticated:
        initial['author'] = request.user.username
        form_class = UserCommentForm
    else:
        form_class = GuestCommentForm
    form = form_class(initial=initial)
    if request.method == 'POST':
        c_form = form_class(request.POST)
        if c_form.is_valid():
            c_form.save()
            messages.add_message(request, messages.SUCCESS, 'Комментарий добавлен')
        else:
            form = c_form
            messages.add_message(request, messages.WARNING, 'Комментарий не добавлен')
    context = {'board': board, 'ais': ais, 'comments': comments, 'form':form}
    return render(request, 'main/detail.html', context)

@login_required()
def profile_board_detail(request, pk):
    board = get_object_or_404(Board, pk=pk)
    ais = board.additionalimage_set.all()
    context = {'board': board, 'ais': ais}
    return render(request, 'main/profile_board_detail.html', context)

@login_required
def profile_board_add(request):
    if request.method == 'POST':
        form = BoardForm(request.POST, request.FILES)
        if form.is_valid():
            board = form.save()
            formset = AIFormSet(request.POST, request.FILES, instance=board) # FILES - словарь полученных з формы данных, для избежания потери изображений
            if formset.is_valid():
                formset.save()
                messages.add_message(request, messages.SUCCESS, 'Объявление добавлено')
                return redirect('main:profile')
    else:
        form = BoardForm(initial={'author': request.user.pk}) # указание автора
        formset = AIFormSet()
    context = {'form': form, 'formset': formset}
    return render(request, 'main/profile_board_add.html', context)

@login_required
def profile_board_change(request, pk):
    board = get_object_or_404(Board, pk)
    if request.method == 'POST':
        form = BoardForm(request.POST, request.FILES, instance=board)
        if form.is_valid():
            board = form.save()
            formset = AIFormSet(request.POST, request.FILES, instance=board)
            if formset.is_valid():
                formset.save()
                messages.add_message(request, messages.SUCCESS, 'Объявление исправлено')
                return redirect('main:profile')
    else:
        form = BoardForm(instance=board)
        formset = AIFormSet(instance=board)
    context = {'form': form, 'formset': formset}
    return render(request, 'main/profile_board_change.html', context)

@login_required
def profile_board_delete(request, pk):
    board = get_object_or_404(Board, pk)
    if request.method == 'POST':
        board.delete()
        messages.add_message(request, messages.SUCCESS, 'Объявление удалено')
        return redirect('main:profile')
    else:
        context = {'board': board}
        return render(request, 'main/profile_board_delete.html', context)

main/templates/main/bad_signature.html
{% extends "layout/basic.html" %}

{% block title %}Ошибка активации{% endblock %}

{% block content %}
<h2>Активация</h2>
<p>Активация пользователя {{ user.username }} прошла неудачно.</p>
<p><a href="{% url 'main:register' %}">Зарегистрироваться повторно</a></p>
{% endblock %}

main/templates/main/by_rubric.html
{% extends "layout/basic.html" %}

{% load thumbnail %}
{% load static %}
{% load bootstrap4 %}

{% block title %}{{ rubric }}{% endblock %}

{% block searchform %}
{% endblock %}

{% block content %}
<h2 class="mb-2">{{ rubric }}</h2>
<div class="container-fluid mb-2">
    <div class="row">
        <div class="col">&nbsp;</div>
        <form class="col-md-auto form-inline">
            {% bootstrap_form form show_label=False %}
            {% bootstrap_button content='Искать' button_type='submit' %}
        </form>
    </div>
</div>
{% if bbs %}
<ul class="list-unstyled">
    {% for bb in bbs %}
    <li class="media my-5 p-3 border">
        {% url 'main:detail' rubric_pk=rubric.pk pk=board.pk as url %}
        <a href="{{ url }}{{ all }}">
        {% if board.image %}
        <img class="mr-3" src="{% thumbnail board.image 'default' %}">
        {% else %}
        <img class="mr-3" src="{% static 'main/empty.jpg' %}">
        {% endif %}
        </a>
        <div class="media-body">
          <h3><a href="{{ url }}{{ all }}">{{ board.title }}</a></h3>
          <div>{{ board.content }}</div>
          <p class="text-right font-weight-bold">{{ board.price }} руб.</p>
          <p class="text-right font-italic">{{ board.created_at }}</p>
        </div>
    </li>
    {% endfor %}
</ul>
{% bootstrap_pagination page url=keyword %}
{% endif %}
{% endblock %}

main/templates/main/change_user_info.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %} Правка личных данных{% endblock %}

{% block content %}
<h2>Правка личных данных пользователя{{ user.username }}</h2>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons submit='Сохранить' %}{% endbuttons %}
</form>
{% endblock %}

main/templates/main/delete_user.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}Удаление пользователя{% endblock %}

{% block content %}
<h2>Удаление пользователя {{ object.username }}</h2>
<form method="post">
    {% csrf_token %}
    {% buttons submit='Удалить' %}{% endbuttons %}
</form>
{% endblock %}

main/templates/main/detail.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}{{ board.title }} - {{ board.rubric.name }}{% endblock %}

{% block content %}
<div class="container-fluid mt-3">
    <div class="row">
        {% if board.image %}
        <div class="col-md-auto"><img src="{{ board.image.url }}" class="main-image"></div>
        {% endif %}
        <div class="col">
            <h2>{{ board.title }}</h2>
            <p>{{ board.content }}</p>
            <p class="font-weight-bold">{{ board.price }} руб.</p>
            <p>{{ board.contacts }}</p>
            <p class="text-right font-italic">Объявление добавлено {{ board.created_at }}</p>
        </div>
    </div>
</div>
{% if ais %}
<div class="d-flex justify-content-between flex-wrap mt-5">
    {% for ai in ais %}
    <div>
        <img class="additional-image" src="{{ ai.image.url }}">
    </div>
    {% endfor %}
</div>
{% endif %}
<p><a href="{% url 'main:by_rubric' pk=board.rubric.pk %}{{ all }}">Назад</a></p>
<h4 class="mt-5">Новый комментарий</h4>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons submit='Добавить' %}{% endbuttons %}
</form>
{% if comments %}
<div class="mt-5">
    {% for comment in comments %}
    <div class="my-2 p-2 border">
        <h5>{{ comment.author }}</h5>
        <p>{{ comment.content }}</p>
        <p class="text-right font-italic">{{ comment.created_at }}</p>
    </div>
    {% endfor %}
</div>
{% endif %}
{% endblock %}

main/templates/main/index.html
{% extends "layout/basic.html" %}

{% block content %}
<h2>Последние 10 объявлений</h2>
{% endblock %}

main/templates/main/logout.html
{% extends "layout/basic.html" %}

{% block title %}Выход{% endblock %}

{% block content %}
<h2>Выход</h2>
<p>Вы успешно вышли с сайта.</p>
{% endblock %}

main/templates/main/profile.html
{% extends "layout/basic.html" %}

{% load thumbnail %}
{% load static %}

{% block title %}Профиль пользователя{% endblock %}

{% block content %}
<h2>Профиль пользователя {{ user.username }}</h2>
{% if user.first_name and user.last_name %}
<p>Здравствуйте, {{ user.first_name }} {{ user.last_name }}!</p>
{% else %}
<p>Здравствуйте!</p>
{% endif %}
<p><a href="{% url 'main:profile_board_add' %}">Добавить объявление</a></p>
{% if boards %}
<h3>Ваши объявления</h3>
<ul class="list-unstyled">
    {% for board in boards %}
    <li class="media my-5 p-3 border">
        {% url 'main:profile_board_detail' pk=board.pk as url %}
        <a href="{{ url }}">
        {% if board.image %}
        <img class="mr-3" src="{% thumbnail board.image 'default' %}">
        {% else %}
        <img class="mr-3" src="{% static 'main/empty.jpg' %}">
        {% endif %}
        </a>
        <div class="media-body">
            <p>Рубрика: {{ board.rubric }}</p>
            <h3><a href="{{ url }}">{{ board.title }}</a></h3>
            <div>{{ board.content }}</div>
            <p class="text-right font-weight-bold">{{ board.price }} руб.</p>
            <p class="text-right font-italic">{{ board.created_at }}</p>
            <p class="text-right mt-2">
                <a href="{% url 'main:profile_board_change' pk=board.pk %}">Исправить</a>
                <a href="{% url 'main:profile_board_delete' pk=board.pk %}">Удалить</a>
            </p>
        </div>
    </li>
    {% endfor %}
</ul>
{% endif %}
{% endblock %}

main/templates/main/profile_board.delete.html
{% extends 'layout/basic.html'%}
{% load static %}
{% block title %}{{ bb.title }}-{{ bb.rubric.name }}{% endblock %}

{% block content %}
<div class="container-fluid mt-3">
    <div class="row">
        {% if bb.image %}
        <div class="col-md-auto">
            <img class="main-image" src="{{ bb.image.url }}" >
        </div>
        {% endif %}
        <div class="col">
            <h2>{{ bb.title }}</h2>
            <p>{{ bb.content }}</p>
            <p class="font-weight-bold">{{ bb.price }}</p>
            <p>{{ bb.contacts }}</p>
            <p class="text-right font-italic">Объявление добавлено {{ bb.created_at }}</p>
        </div>
    </div>
</div>
{% if ais %}
<div class="d-flex justify-content-between flex-wrap mt-5">
    {% for ai in ais %}
    <div>
        <img class="additional-image" src="{{ ai.image.url }}">
    </div>
    {% endfor %}
</div>
{% endif %}
<p><a href="{% url 'main:by_rubric' pk=bb.rubric.pk%}{{ all }}">
    Назад
</a></p>
{% endblock %}

main/templates/main/profile_board_add.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}Добавление объявления - Профиль пользователя{% endblock %}

{% block content %}
<h2><a href="{% url 'main:profile_board_add' %}">Добавление объявления</a></h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% bootstrap_formset formset layout='horizontal' %}
    {% buttons submit='Добавить' %}{% endbuttons %}
</form>
{% endblock %}

main/templates/main/profile_board_delete.html
{% extends 'layout/basic.html'%}
{% load static %}
{% block title %}{{ bb.title }}-{{ bb.rubric.name }}{% endblock %}

{% block content %}
<div class="container-fluid mt-3">
    <div class="row">
        {% if bb.image %}
        <div class="col-md-auto">
            <img class="main-image" src="{{ bb.image.url }}" >
        </div>
        {% endif %}
        <div class="col">
            <h2>{{ bb.title }}</h2>
            <p>{{ bb.content }}</p>
            <p class="font-weight-bold">{{ bb.price }}</p>
            <p>{{ bb.contacts }}</p>
            <p class="text-right font-italic">Объявление добавлено {{ bb.created_at }}</p>
        </div>
    </div>
</div>
{% if ais %}
<div class="d-flex justify-content-between flex-wrap mt-5">
    {% for ai in ais %}
    <div>
        <img class="additional-image" src="{{ ai.image.url }}">
    </div>
    {% endfor %}
</div>
{% endif %}
<p><a href="{% url 'main:by_rubric' pk=bb.rubric.pk%}{{ all }}">
    Назад
</a></p>
{% endblock %}

main/templates/main/profile_board_detail.html
{% extends "layout/basic.html" %}

{% block title %}{{ bb.title }} - Профиль пользователя{% endblock %}

{% block content %}
<div class="container-fluid mt-3">
    <div class="row">
        {% if board.image %}
        <div class="col-md-auto"><img src="{{ board.image.url }}" class="main-image"></div>
        {% endif %}
        <div class="col">
            <h2>{{ board.title }}</h2>
            <p>{{ board.content }}</p>
            <p class="font-weight-bold">{{ board.price }} руб.</p>
            <p>{{ bb.contacts }}</p>
            <p class="text-right font-italic">Объявление добавлено {{ board.created_at }}</p>
        </div>
    </div>
</div>
{% if ais %}
<div class="d-flex justify-content-between flex-wrap mt-5">
    {% for ai in ais %}
    <div>
        <img class="additional-image" src="{{ ai.image.url }}">
    </div>
    {% endfor %}
</div>
{% endif %}
<p><a href="{% url 'main:profile' %}">Назад</a></p>
{% if comments %}
<div class="mt-5">
    {% for comment in comments %}
    <div class="my-2 p-2 border">
        <h5>{{ comment.author }}</h5>
        <p>{{ comment.content }}</p>
        <p class="text-right font-italic">{{ comment.created_at }}</p>
    </div>
    {% endfor %}
</div>
{% endif %}
{% endblock %}

main/templates/main/register_done.html
{% extends "layout/basic.html" %}

{% block title %}Регистрация{% endblock %}

{% block content %}
<p>Регистрация пользователя завершена.</p>
<p>На адрес электронной почты, указаный пользователем, выслано письмо для активации.</p>
{% endblock %}

main/templates/main/register_user.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}Регистрация{% endblock %}

{% block content %}

<h2>Регистрация нового пользователя</h2>

<form method="POST">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons submit='Зарегистрироваться' %} {% endbuttons %}
</form>

{% endblock %}